"""add mtime to lyrics

Revision ID: 177173f9d625
Revises: 8118058f226a
Create Date: 2026-05-19 04:10:41.870227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from lyrics_utils import fetch_override
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = '177173f9d625'
down_revision: Union[str, None] = '8118058f226a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lyrics', sa.Column('mtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT song, artist from lyrics")).fetchall()
    breakpoint()
    for row in rows:
        mtime, lyrics = fetch_override(row.song, row.artist)
        if not lyrics:
            mtime = datetime.now()
        bind.execute(
            sa.text("UPDATE lyrics SET mtime = :mtime where song = :song and artist = :artist"),
            {"mtime": mtime, "song": row.song, "artist": row.artist}
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lyrics', 'mtime')
    # ### end Alembic commands ###
